import FreeSimpleGUI as sg
label1=sg.Text("select files to compress")
input=sg.Input()
choose_button=sg.FilesBrowse("Choose")
label2=sg.Text("select destination folder ")
input2=sg.Input()
choose_button2=sg.FolderBrowse("Choose")
windows=sg.Window("File Compressor",layout=[[label1,input,choose_button],[label2,input2,choose_button2]])
windows.read()
windows.close()